export const TestStreamerList = [
  { _id: 1, member: "실프" },
  { _id: 2, member: "김진우" },
  { _id: 3, member: "김뚜띠" },
  { _id: 4, member: "한동숙" },
  { _id: 5, member: "탬탬버린" },
  { _id: 6, member: "이춘향" },
  { _id: 7, member: "마뫄" },
  { _id: 8, member: "눈꽃" },
  { _id: 9, member: "괴물쥐" },
  { _id: 10, member: "명예훈장" },
  { _id: 11, member: "다주" },
  { _id: 12, member: "채현찌" },
  { _id: 13, member: "너불" },
  { _id: 14, member: "강지" },
  { _id: 15, member: "아야츠노 유니" },
  { _id: 16, member: "나나양" },
  { _id: 17, member: "서새봄" },
  { _id: 18, member: "서넹" },
  { _id: 19, member: "임나은" },
  { _id: 20, member: "포셔" },
  { _id: 21, member: "이초홍" },
  { _id: 22, member: "노돌리" },
  { _id: 23, member: "삼식" },
  { _id: 24, member: "삐부" },
];
